Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: c6gn.2xlarge
  #DisableSimultaneousMultithreading: true
  Networking:
    SubnetId: subnet-ce9a7ca8
  LocalStorage:
    RootVolume:
       Size: 100
       VolumeType: gp3
  Ssh:
    KeyName: dalessiofkey
  Dcv:
    Enabled: true

  CustomActions:
    OnNodeConfigured:
      Script: https://raw.githubusercontent.com/aws-samples/hpc-workshop-wrf/pcv3-vrfv4/pc_setup_scripts/git_download_and_run.sh
      Args:
        - https://github.com/aws-samples/hpc-workshop-wrf.git,setup.sh
 
SharedStorage:
  - MountDir: /shared
    Name: shared  
    StorageType: Ebs
    EbsSettings:
       VolumeType: gp3
       Size: 100
    
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: c6gn
    ComputeResources:
    - Name: c6gn
      InstanceType: c6gn.16xlarge
      MinCount: 0
      MaxCount: 6
      Efa:
        Enabled: true
    Networking:
      SubnetIds:
      - subnet-ce9a7ca8
      PlacementGroup:
        Enabled: true
